    IS =   {'Abbot', 'Getz 1', 'Porter', ...              
       'Abbot 1',    'Getz 2', 'PourquoiPas', ...
       'Abbot 2', 'Gillet', 'Prince Harald', ...        
       'Abbot 3', 'Hamilton', 'Publications', ...         
       'Abbot 4', 'Hamilton Piedmont', 'Quar', ...                   
       'Abbot 5', 'Hannan', 'Quatermain Point', ...       
       'Abbot 6', 'HarbordGlacier', 'Rayner Thyer', ...   
       'Ainsworth', 'Harmon Bay', 'Rennick', ...
       'Alison', 'Hayes Coats Coast', 'Richter', ...
       'Amery', 'Helen', 'Riiser-Larsen', ...
       'Andreyev', 'Holmes', 'Ronne', ...
       'Arneb', 'Holt', 'Rose Point', ...
       'Astrolabe', 'HornBluff', 'Ross', ...
       'Atka', 'Hoseason', ...
       'Aviator', 'Hovde', 'Rund Bay', ...
       'Bach', 'Hull', 'Rydberg Peninsula 1', ...
       'Barber', 'Hummer Point', 'Rydberg Peninsula 2', ...
       'Baudouin', 'Ironside', 'Sandford', ...
       'Borchgrevink', 'Jackson', 'Shackleton', ...
       'Brahms', 'Jelbart', 'Shirase', ...
       'Britten', 'Kirkby', 'Skallen', ...
       'Brunt Stancomb', 'Land', 'Slava', ...
       'Campbell', 'LarsenA', 'SmithInlet', ...
       'CapeWashington', 'LarsenB', 'Sorsdal', ...
       'Cheetham', 'LarsenC', 'Stange', ...
       'Chugunov', 'LarsenD', 'Sulzberger', ...
       'Cirque Fjord', 'LarsenD 1', 'Suter', ...
       'ClarkeBay', 'LarsenE', 'Suvorov', ...
       'Commandant Charcot', 'LarsenF', 'Swinburne', ...
       'Conger Glenzer', 'LarsenG', 'Telen', ...
       'Cook', 'Lauritzen', 'Thomson', ...
       'Cosgrove', 'Lazarev', 'Thwaites', ...
       'Crosson', 'Lillie', 'Tinker', ...
       'Dalk', 'Liotard', 'Totten', ...
       'Dawson Lambton', 'Mandible Cirque', 'Tracy Tremenchus', ...
       'Deakin', 'Manhaul', 'Tucker', ...
       'Dennistoun', 'Marin', 'Underwood', ...
       'Dibble', 'Mariner', 'Utsikkar', ...
       'Dotson', 'Marret', 'Venable', ...
       'Drury', 'Matusevitch', 'Verdi', ...
       'Drygalski', 'May Glacier', 'Vigrid', ...
       'Edward VIII', 'McLeod', 'Vincennes Bay', ...
       'Ekstrom', 'Mendelssohn', 'Voyeykov', ...
       'Eltanin Bay', 'Mertz', 'Walgreen Coast 1', ...
       'Erebus', 'Morse', 'Walgreen Coast 2', ...
       'Falkner', 'Moscow University', 'WattBay', ...
       'Ferrigno', 'Moubray', 'West', ...
       'Filchner', 'Mulebreen', 'Whittle', ...
       'Fimbul', 'Myers', 'Wilkins', ...
       'Fisher', 'Nansen', 'Williamson', ...
       'Fitzgerald', 'Nickerson', 'WilmaRobertDowner', ...
       'Flatnes' 'Fox Glacier', 'Ninnis', 'Withrow', ...
       'Fox Ice Stream', 'Nivl', 'Wordie (Airy Rotz Seller)', ...
       'Francais', 'Noll', 'Wordie (Cape Jeremy)', ...
       'Frost', 'Nordenskjold', 'Wordie (Harriott)', ...
       'Gannutz', 'Parker', 'Wordie (Harriott Headland)', ...
       'Garfield', 'Paternostro', 'Wordie (Prospect)', ...
       'GeikieInlet', 'Perkins', 'Wylde', ...
       'George VI', 'Philbin Inlet', 'Zelee', ...        
       'Getz', 'Pine Island', 'Zubchatyy'}; 